        @yield('css')
        @include('admin::admin.partials.header')
        @include('admin::admin.partials.sidebar')
        @yield('content')
        @include('admin::admin.partials.footer')
       @yield('script')